---
# vars file for RedisCluster
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
docker_compose_version: "2.6.0"
#######variable master
master_host: "{{ hostvars[master:]['ansible_default_ipv4']['address'] }}"
slave_host:  "{{ hostvars[slave:]['ansible_default_ipv4']['address'] }}"
path_master_redis: /root/master-redis
path_slave_redis: /root/slave-redis
