
# Host format:
# 172.1.1.2 clusterhost=redis01

[all:vars]

[master]
10.235.225.76  clusterhost=master
[slave]

10.235.225.135  clusterhost=slave

[redis_nodes:children]
#master

[redis_nodes]
#172.24.32.83 clusterhost=redis01
#172.24.32.84 clusterhost=redis02
#172.24.32.85 clusterhost=redis03
