- name: Allow Redis to listen on tcp port {{ redis_port }}
  seport:
    ports: "{{ redis_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  become: true

- name: Allow Redis-Sentinel to listen on tcp port {{ sentinel_port }}
  seport:
    ports: "{{ sentinel_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  become: true
